package com.linkforge.domain.workflow;

public enum WorkflowStage {
    INTAKE,
    SCENARIO_CLASSIFICATION,
    CODEBASE_INSPECTION,
    REQUIREMENT_INTERPRETATION,
    TASK_PLANNING,
    SPECIALIST_COORDINATION,
    FINISHED
}
