package com.linkforge.domain.workflow;

public enum WorkflowStage {
    INTAKE,
    SCENARIO_CLASSIFICATION,
    CODEBASE_INSPECTION,
    REQUIREMENT_INTERPRETATION,
    TASK_PLANNING,
    IMPLEMENTATION_PROPOSAL,
    PLAN_APPROVAL,
    SPECIALIST_COORDINATION,
    IMPLEMENTATION_APPLICATION,
    BUILD_VALIDATION,
    REPAIR_APPROVAL,
    FINISHED,
    ROLLED_BACK,
    BLOCKED,
    CANCELLED
}
